### ISSUE TITLE
Basic CI setup

### ISSUE THREAD

**Issue by 4face-studi0** [androiddevelopersitalia/aditogether#31]
Using GitHub Actions

- [x] lint
- [ ] ~build~ nothing to build as now
- [x] unit tests

**Comment by fondesa** [comment]
This is a big topic and requires a long discussion but few early comments on this:
- currently build-tools can't run our linters on themselves (this can be solved in multiple ways)
- are we running build and test in debug, release or both? Maybe we can start running them just in release
- are we running tests on PRs only or also post merge? We have a free plan with GitHub actions

**Comment by 4face-studi0** [comment]
All valid points!

In my opinion, as a basic setup, we could start with:
* The first could be a separate ticket
* I would run debug only, as we probably not gonna build release for a while, and building release would be more "expensive"
* I would run on PR and on `main`. I don't this can become an issue anytime some, especially considering the lightweight pipeline

**Comment by fondesa** [comment]
Yes, the one you proposed can be a good first setup, we can improve from there.

**Comment by 4face-studi0** [comment]
Do you agree on building/testing debug? Or you see more value using release?

**Comment by fondesa** [comment]
I agree on building/testing in debug at the start
